### ISSUE TITLE
Error in docker-compose.yml after #5

### ISSUE THREAD

**Issue by AndreMaz** [moleculerjs/moleculer-template-project#6]
Hey @intech . It seems that PR https://github.com/moleculerjs/moleculer-template-project/pull/5 has a slight problem in `docker-compose.yml`. For some reason it generates entries like this:
```yml
networks:
  internal:
```

Current:
```yml
version: "3.7"

services:
  api:
    build:
      context: .
    image: moleculer-demo
    container_name: moleculer-demo-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - internal

  greeter:
    build:
      context: .
    image: moleculer-demo
    container_name: moleculer-demo-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats

  networks:
    - internal

  nats:
    image: nats
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - internal
      - default

networks:
  internal:
```

Running `npm run dc:up` produces the following error:
```
ERROR: In file '.\docker-compose.yml', service 'networks' must be a mapping not an array.
```

To get things working again I had to remove all references about `network`
```yml
version: "3.7"

services:
  api:
    build:
      context: .
    image: moleculer-demo
    container_name: moleculer-demo-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  greeter:
    build:
      context: .
    image: moleculer-demo
    container_name: moleculer-demo-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats

  nats:
    image: nats
    labels:
      - "traefik.enable=false"

  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
```

Can you please  fix it?
